### ISSUE TITLE
GDBMultiNonStopRunControlTest.testSuspendProcessTwoThreadsRunning[gdbserver] is unstable

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt/cdt#119]
This test regularly fails on Jenkins with this error:

**Error Message**
Timed out waiting for ServiceEvent: org.eclipse.cdt.dsf.mi.service.command.events.MIStoppedEvent
**Stacktrace**

> java.lang.Exception: Timed out waiting for ServiceEvent: org.eclipse.cdt.dsf.mi.service.command.events.MIStoppedEvent
> 	at org.eclipse.cdt.tests.dsf.gdb.tests.nonstop.GDBMultiNonStopRunControlTest.testSuspendProcessTwoThreadsRunning(GDBMultiNonStopRunControlTest.java:3238)

**Standard Output**
168,523 "testSuspendProcessTwoThreadsRunning[gdbserver]" requesting gdb with gdbserver. Launched gdb 8.1.1.

**Comment by jonahgraham** [comment]
It failed again on [Jenkins](https://ci.eclipse.org/cdt/job/cdt/job/main/84/testReport/junit/org.eclipse.cdt.tests.dsf.gdb.tests.nonstop/GDBMultiNonStopRunControlTest/testSuspendProcessTwoThreadsRunning_gdbserver_10_/)

```
java.lang.Exception: Timed out waiting for ServiceEvent: org.eclipse.cdt.dsf.mi.service.command.events.MIStoppedEvent
	at org.eclipse.cdt.tests.dsf.gdb.tests.nonstop.GDBMultiNonStopRunControlTest.testSuspendProcessTwoThreadsRunning(GDBMultiNonStopRunControlTest.java:3238)
```

I think this is because although I [increased](https://github.com/eclipse-cdt/cdt/commit/10e95a182506740eabb9d4298ae2082ac9af15c5) the time the process would stay alive for, I also need to increase how long to wait for.
