### ISSUE TITLE
Internal error while trying to serialize language settings Resource '/noFilesToBuild' does not exist.

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt/cdt#163]
When running test cases sometimes I see:

`Internal error while trying to serialize language settings Resource '/noFilesToBuild' does not exist.`

as part of the failing test.

e.g.:

<details>
<summary>test30NoFilesToBuild (org.eclipse.cdt.managedbuilder.core.tests.ManagedProject30MakefileTests) failed</summary>

```java
Expected number (0) of Non-OK status objects in log differs from actual (1).
 Internal error while trying to serialize language settings Resource '/noFilesToBuild' does not exist.
Stack Trace
org.eclipse.core.internal.resources.ResourceException(/noFilesToBuild)[368]: java.lang.Exception: Resource '/noFilesToBuild' does not exist.
 at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
 at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
 at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:330)
 at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:204)
 at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:150)
 at org.eclipse.core.internal.resources.Folder.assertCreateRequirements(Folder.java:36)
 at org.eclipse.core.internal.resources.Folder.create(Folder.java:94)
 at org.eclipse.core.internal.resources.Folder.create(Folder.java:122)
 at org.eclipse.cdt.internal.core.language.settings.providers.LanguageSettingsProvidersSerializer.serializeLanguageSettings(LanguageSettingsProvidersSerializer.java:909)
 at org.eclipse.cdt.internal.core.settings.model.xml.XmlProjectDescriptionStorage$DesSerializationRunnable.run(XmlProjectDescriptionStorage.java:178)
 at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager$CompositeWorkspaceRunnable.run(CProjectDescriptionManager.java:204)
 at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager$CompositeWorkspaceRunnable.run(CProjectDescriptionManager.java:204)
 at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager$5.run(CProjectDescriptionManager.java:508)
 at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
 at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.runAtomic(CProjectDescriptionManager.java:504)
 at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager$4.run(CProjectDescriptionManager.java:484)
 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
junit.framework.AssertionFailedError: 
Expected number (0) of Non-OK status objects in log differs from actual (1).
	Internal error while trying to serialize language settings Resource '/noFilesToBuild' does not exist.
Stack Trace
org.eclipse.core.internal.resources.ResourceException(/noFilesToBuild)[368]: java.lang.Exception: Resource '/noFilesToBuild' does not exist.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:330)
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:204)
	at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:150)
	at org.eclipse.core.internal.resources.Folder.assertCreateRequirements(Folder.java:36)
	at org.eclipse.core.internal.resources.Folder.create(Folder.java:94)
	at org.eclipse.core.internal.resources.Folder.create(Folder.java:122)
	at org.eclipse.cdt.internal.core.language.settings.providers.LanguageSettingsProvidersSerializer.serializeLanguageSettings(LanguageSettingsProvidersSerializer.java:909)
	at org.eclipse.cdt.internal.core.settings.model.xml.XmlProjectDescriptionStorage$DesSerializationRunnable.run(XmlProjectDescriptionStorage.java:178)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager$CompositeWorkspaceRunnable.run(CProjectDescriptionManager.java:204)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager$CompositeWorkspaceRunnable.run(CProjectDescriptionManager.java:204)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager$5.run(CProjectDescriptionManager.java:508)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.runAtomic(CProjectDescriptionManager.java:504)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager$4.run(CProjectDescriptionManager.java:484)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)



Caused by: org.eclipse.core.internal.resources.ResourceException: Resource '/noFilesToBuild' does not exist.
Caused by: java.lang.Exception: Resource '/noFilesToBuild' does not exist.
```

</details>

Follow-on from #117

**Comment by jonahgraham** [comment]
This happens because of a race condition between the scanner discovery and the project getting deleted at the end of a test. If you change the schedule call at the end of `org.eclipse.cdt.managedbuilder.language.settings.providers.AbstractBuiltinSpecsDetector.execute()` you can reproduce this, or similar problems, quite easily.

To fix it, probably more checks needed in the specs runner to bail out if the project is gone (or the workbench is shutdown)
