### ISSUE TITLE
importSimpleCMakeProject (org.eclipse.cdt.cmake.ui.internal.tests.NewCMakeProjectTest) failed

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt/cdt#169]
The test `importSimpleCMakeProject (org.eclipse.cdt.cmake.ui.internal.tests.NewCMakeProjectTest) failed` is unstable, maybe just since updating to M3 of Orbit?

```
Project type was not detected ==> expected: <CMake Project> but was: <>
org.opentest4j.AssertionFailedError: Project type was not detected ==> expected: <CMake Project> but was: <>
	at org.eclipse.cdt.cmake.ui.internal.tests.NewCMakeProjectTest.importCMakeProject(NewCMakeProjectTest.java:171)
	at org.eclipse.cdt.cmake.ui.internal.tests.NewCMakeProjectTest.importSimpleCMakeProject(NewCMakeProjectTest.java:141)
```

**Comment by jonahgraham** [comment]
Failed again https://github.com/eclipse-cdt/cdt/runs/9620897872 for #171
