### ISSUE TITLE
ConcurrentModificationException in LaunchBarManager.storeActiveDescriptor()

### ISSUE THREAD

**Issue by trancexpress** [eclipse-cdt/cdt#262]
**Describe the bug**
During our ARTs, we encountered the following CME:

```
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:778)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.storeActiveDescriptor(LaunchBarManager.java:511)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.setActiveLaunchDescriptor(LaunchBarManager.java:487)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.addDescriptor(LaunchBarManager.java:309)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.launchObjectAdded(LaunchBarManager.java:358)
	at org.eclipse.launchbar.core.internal.LaunchBarManager.launchConfigurationAdded(LaunchBarManager.java:899)
	at org.eclipse.debug.internal.core.LaunchManager$ConfigurationNotifier.run(LaunchManager.java:219)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.internal.core.LaunchManager$ConfigurationNotifier.notify(LaunchManager.java:209)
	at org.eclipse.debug.internal.core.LaunchManager.launchConfigurationAdded(LaunchManager.java:2120)
	at org.eclipse.debug.internal.core.LaunchConfigurationWorkingCopy.writeNewFile(LaunchConfigurationWorkingCopy.java:375)
	at org.eclipse.debug.internal.core.LaunchConfigurationWorkingCopy.doSave0(LaunchConfigurationWorkingCopy.java:259)
	at org.eclipse.debug.internal.core.LaunchConfigurationWorkingCopy.doSave(LaunchConfigurationWorkingCopy.java:229)
	at org.eclipse.debug.internal.core.LaunchConfigurationWorkingCopy.doSave(LaunchConfigurationWorkingCopy.java:187)
        ...
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

The above is triggered from one of our plug-ins, while creating a launch configuration (and saving it).

If I debug the respective test, I see also a job is trying to change the container in question:

```
"Worker-21: Launching AttachDebug" #206 prio=5 os_prio=0 cpu=51.90ms elapsed=102.18s tid=0x00005555556a9ee0 nid=0x5f8c at breakpoint [0x00007fff74ef9000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.launchbar.core.internal.LaunchBarManager.doSetActiveLaunchDescriptor(LaunchBarManager.java:501)
        at org.eclipse.launchbar.core.internal.LaunchBarManager.setActive(LaunchBarManager.java:443)
        at org.eclipse.launchbar.core.internal.LaunchBarManager$2.launchAdded(LaunchBarManager.java:172)
        at org.eclipse.debug.internal.core.LaunchManager$LaunchNotifier.run(LaunchManager.java:425)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.debug.internal.core.LaunchManager$LaunchNotifier.notify(LaunchManager.java:415)
        at org.eclipse.debug.internal.core.LaunchManager.fireUpdate(LaunchManager.java:1046)
        at org.eclipse.debug.internal.core.LaunchManager.addLaunch(LaunchManager.java:693)
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:764)
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:717)
        at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1040)
        at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1243)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I can't reproduce the race conditions itself though.

**Expected behavior**
No CME occurrs.

**Comment by jonahgraham** [comment]
@trancexpress I merged the change now, if you want to cleanup that code further I would be happy to review such changes too.
