### ISSUE TITLE
PathSettingsContainer.removeChildContainer does a call to getValue to get a value that is never used

### ISSUE THREAD

**Issue by jantje** [eclipse-cdt/cdt#430]
When investigating #356 I found that one of the exceptions I get is from PathSettingsContainer.removeChildContainer code (copied below) which does a call to getValue in case the object has been found.
```
	public Object removeChildContainer(IPath path) {
		PathSettingsContainer container = getChildContainer(path, false, true);
		Object value = null;
		if (container != null) {
			value = container.getValue();
			container.remove();
		}
		return value;
	}
```
This is done to return the removed child. However getValue throws an error when the value equals INEXISTENT_VALUE.
The result is that an error is thrown when a invalid value is removed :-(
```
	public Object getValue() {
		if (fValue == INEXISTENT_VALUE)
			throw new IllegalStateException();
		return fValue;
	}
```
Upon further inspection I found the returned value is never used.
I accept this is a problem in my code (which for some unknown reason set the value on INEXISTENT_VALUE) but I do think it would be better not to get the value that is never used.
```
!ENTRY org.eclipse.jface 4 2 2023-06-20 19:38:01.448
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.IllegalStateException
	at org.eclipse.cdt.core.settings.model.util.PathSettingsContainer.getValue(PathSettingsContainer.java:608)
	at org.eclipse.cdt.core.settings.model.util.PathSettingsContainer.removeChildContainer(PathSettingsContainer.java:293)
	at org.eclipse.cdt.internal.core.settings.model.CfgProxyCache.removeCachedProxy(CfgProxyCache.java:111)
	at org.eclipse.cdt.internal.core.settings.model.ProxyProvider.fillCache(ProxyProvider.java:79)
	at org.eclipse.cdt.internal.core.settings.model.ProxyProvider.cacheValues(ProxyProvider.java:132)
	at org.eclipse.cdt.internal.core.settings.model.ProviderBasedRcDesHolder.getCurrentResourceDescription(ProviderBasedRcDesHolder.java:49)
	at org.eclipse.cdt.internal.core.settings.model.CConfigurationDescription.getRootFolderDescription(CConfigurationDescription.java:249)
	at org.eclipse.cdt.ui.newui.AbstractPage.getResDesc(AbstractPage.java:1002)
	at org.eclipse.cdt.ui.newui.AbstractPage.cfgChanged(AbstractPage.java:1041)
	at org.eclipse.cdt.ui.newui.AbstractPage.handleConfigSelection(AbstractPage.java:483)
	at org.eclipse.cdt.ui.newui.AbstractPage.populateConfigurations(AbstractPage.java:828)
	at org.eclipse.cdt.ui.newui.AbstractPage.setVisible(AbstractPage.java:861)
	at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1263)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:630)
	at org.eclipse.jface.preference.PreferenceDialog$5.lambda$0(PreferenceDialog.java:660)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.jface.preference.PreferenceDialog$5.selectionChanged(PreferenceDialog.java:657)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:821)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:818)
	at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1191)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:284)
	at org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:438)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:155)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:121)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:580)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:647)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:439)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1286)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmSysChar(Widget.java:2351)
	at org.eclipse.swt.widgets.Control.WM_SYSCHAR(Control.java:5451)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4821)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6142)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5022)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3640)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:53)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:48)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by jantje** [comment]
I investigated more deeply and I found out (not yet completely) what is going on.
When opening the project properties c/c++ build settings in autobuild the first time fillcache is called fScope.getChildren returns 3 items
![afbeelding](https://github.com/eclipse-cdt/cdt/assets/1175841/a8999300-4c10-4e43-b403-3d29e86ce204)

Among those is a folder description that is the root folder.

Due to a cfg change (which I don't know why it happens but you know this happens a  lot) we get back to the same code but now fScope.getchildren only returns 2 items
![afbeelding](https://github.com/eclipse-cdt/cdt/assets/1175841/d1fed27f-ac55-46ce-bdfe-f0ac16028b96)

the folder description is gone.
As you can see below none of the first items are the same the second time so all of them are removed from the map.
![afbeelding](https://github.com/eclipse-cdt/cdt/assets/1175841/683105cf-5b0d-4b76-9f4e-4c3709bc4aa2)
Removing from the map involves setting the value to INEXISTENT_VALUE and the folder description value seems to be the project resource descriptor
![afbeelding](https://github.com/eclipse-cdt/cdt/assets/1175841/f0fd55e9-5956-46ee-b6ad-10359b51666f)


Looking deeper you can see that the first time fScope.getChildren() is called data is taken from a CConfigurationDescriptionCache
![afbeelding](https://github.com/eclipse-cdt/cdt/assets/1175841/07393c8b-3774-407c-adfe-f61b9f6266fc)

However the second time the data is gathered from my AutoBuildConfigurationDescription
![afbeelding](https://github.com/eclipse-cdt/cdt/assets/1175841/636e3970-ff5f-495d-aea7-a5cdd2c5acf0)

And because my implementation of getResourceDatas returns an empty list and the one from CConfigurationDescriptionCache returns a folder description of root I now understand the behaviour.

This raises some questions
1) why does the configuration first has data of the type CConfigurationDescriptionCache and then from AutoBuildConfigurationDescription (what it should be from the start)
2) Why is fRcHolder.fPathSettingsContainer in the cache?
3) Why is there so much caching going on?

**Comment by jantje** [comment]
For question 1
What I see is: when I call
```
	@Override
	public CConfigurationData getConfigurationData() {
		CConfigurationData data = getConfigurationData(true);
		if (data instanceof CConfigurationDescriptionCache) {
			data = ((CConfigurationDescriptionCache) data).getConfigurationData();
		}
		return data;
	}
```
To get my autobuildConfiguration the data object used in the remark above gets changed.
As I call getConfigurationData in updateData (IMHO the way for me to get to my data) this is after the page creation and explains why the cache needed to be flushed and rebuild.
All this caching makes the code really unreadable/unmaintainable.
I also wonder: would it not be better to get all the referenced editable datas to a write state when getting CConfigurationDescription to write?

**Comment by jantje** [comment]
As to question 2 (not fully answered but close enough)
https://github.com/eclipse-cdt/cdt/blob/9edc432c49a1d6b239850cef4c61db3cd1a15fe3/core/org.eclipse.cdt.core/model/org/eclipse/cdt/core/settings/model/extension/impl/CDefaultConfigurationData.java#L116-L125

The copySettingsFrom explicitly adds base.getRootFolderData() and then does not add it again when adding RcDatas
I'm not sure what the implications of this are
But one is sure 
If you implement a CConfigurationData
getResourceDatas needs to contain what it returns in getRootFolderData
And that is why this issue popped up in AutoBuild

**Comment by jantje** [comment]
2 is not fully answered because it does not answer: why is fRcHolder.fPathSettingsContainer in the cache?
I mean getRootFolderData returns the root folder  (/) so the value of fRcHolder.fPathSettingsContainer is in the list.
But why is the exact object ending up in the cache? That is not yet answered by the story above.

**Comment by jonahgraham** [comment]
> please advice whether these would be acceptable changes for CDT

I wanted to acknowledge I saw this request, but let you know that I don't have much time to review this code. Changing this method signature is certainly out of scope for an 11.x release as it is API.

I have not read through the rest of this issue. I recommend you reach out to some of the people who said they were interested in this new framework. If a PR is reviewed by knowledgeable/interested people (even if not committers) then we can consider merging such PRs.

**Comment by jantje** [comment]
>I wanted to acknowledge I saw this request,

That is really appreciated
