### ISSUE TITLE
Eclipse CDT's Oomph setup not working

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt/cdt#511]
The Eclipse CDT Oomph setup is not working (As reported in https://github.com/eclipse-cdt/cdt/pull/508#issuecomment-1679399920)

**Comment by jonahgraham** [comment]
The OP (in #508) didn't report a specific error, but I see this:

```
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:151)
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:905)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
    ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1692407598597
    ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: org.eclipse.cdt.debug.application.product 11.3.0.v20230818-211316 requires 'osgi.bundle; jakarta.activation-api 0.0.0' but it could not be found
    ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
      ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1692407598597
      ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.cdt.debug.application.product 0.0.0
```

**Comment by jonahgraham** [comment]
@mmx85 Please try again (in a couple of hours) with Oomph and reopen/comment if there are still issues you face.

**Comment by mmx85** [comment]
Hi Jonah.
I have just verified the fix and I can still reproduce the issue. I have attached the screenshot.
![eclipse-cdt-install-issue](https://github.com/eclipse-cdt/cdt/assets/17565870/b9b2b420-5aa9-46d7-8721-c0aae4d0cf34)

**Comment by jonahgraham** [comment]
Hmm - the fix in #520 specifically changed the URL to fix this, but your screenshot still shows it using the old URL. I have tested that and can see the same.

It looks like the sync script didn't run. I'll look into that and get back to you asap.

**Comment by jonahgraham** [comment]
Looks like the job that syncs the cdt.setup to the installer broke last week as the job hasn't run successfully recently. https://ci.eclipse.org/oomph/job/setup-archiver/ 

This is handled by the oomph project and I have raised an issue with them:

- https://github.com/eclipse-oomph/oomph/issues/21

**Comment by jonahgraham** [comment]
It works again - make sure to press update in the installer to ensure you have latest version:

![image](https://github.com/eclipse-cdt/cdt/assets/679236/85343d9b-e5e6-4d33-bd95-2b56df72a91e)

**Comment by mmx85** [comment]
Now it works fine.
Thank you.

чт, 24 серп. 2023, 21:28 користувач Jonah Graham ***@***.***>
пише:
