### ISSUE TITLE
click LaunchBar's edit button in the toolbars to open the junit testcase show an error dialog

### ISSUE THREAD

**Issue by MrLiuzy** [eclipse-cdt/cdt#555]
The LaunchBar's edit button cannot open a junit launch configuration dialog, but can open the Java Application and Maven launch configuartion dialog. Error Log record some errors.

version: eclipse-jee-2023-09-R-win32-x86_64
os: windows11
```
null
org.eclipse.ui
Error
Thu Sep 14 15:37:03 CST 2023
Unhandled event loop exception

java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Button.setEnabled(boolean)" because the return value of "org.eclipse.launchbar.ui.internal.LaunchBarLaunchConfigDialog.getButton(int)" is null
	at org.eclipse.launchbar.ui.internal.LaunchBarLaunchConfigDialog.run(LaunchBarLaunchConfigDialog.java:332)
	at org.eclipse.jdt.internal.junit.util.TestSearchEngine.findTestMethods(TestSearchEngine.java:77)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationTab.calculateMethodsCache(JUnitLaunchConfigurationTab.java:802)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationTab.initializeFrom(JUnitLaunchConfigurationTab.java:490)
	at org.eclipse.debug.ui.AbstractLaunchConfigurationTabGroup.initializeFrom(AbstractLaunchConfigurationTabGroup.java:93)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupWrapper.initializeFrom(LaunchConfigurationTabGroupWrapper.java:182)
	at org.eclipse.launchbar.ui.internal.LaunchBarLaunchConfigDialog.createDialogArea(LaunchBarLaunchConfigDialog.java:191)
	at org.eclipse.jface.dialogs.TitleAreaDialog.createContents(TitleAreaDialog.java:166)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.eclipse.launchbar.ui.internal.LaunchBarUIManager.openConfigurationEditor(LaunchBarUIManager.java:134)
	at org.eclipse.launchbar.ui.controls.internal.ConfigSelector.handleEdit(ConfigSelector.java:156)
	at org.eclipse.launchbar.ui.controls.internal.CSelector$5.lambda$0(CSelector.java:265)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```
```
null
org.eclipse.jface
Error
Thu Sep 14 15:37:03 CST 2023
Problems occurred when invoking code from plug-in: "org.eclipse.jface".

java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Button.setEnabled(boolean)" because the return value of "org.eclipse.launchbar.ui.internal.LaunchBarLaunchConfigDialog.getButton(int)" is null
	at org.eclipse.launchbar.ui.internal.LaunchBarLaunchConfigDialog.run(LaunchBarLaunchConfigDialog.java:332)
	at org.eclipse.jdt.internal.junit.util.TestSearchEngine.findTestMethods(TestSearchEngine.java:77)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationTab.calculateMethodsCache(JUnitLaunchConfigurationTab.java:802)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationTab.lambda$0(JUnitLaunchConfigurationTab.java:269)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:159)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:156)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2143)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1675)
	at org.eclipse.jface.viewers.Viewer.setSelection(Viewer.java:384)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationTab.updateTestLoaderFromConfig(JUnitLaunchConfigurationTab.java:507)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationTab.initializeFrom(JUnitLaunchConfigurationTab.java:488)
	at org.eclipse.debug.ui.AbstractLaunchConfigurationTabGroup.initializeFrom(AbstractLaunchConfigurationTabGroup.java:93)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupWrapper.initializeFrom(LaunchConfigurationTabGroupWrapper.java:182)
	at org.eclipse.launchbar.ui.internal.LaunchBarLaunchConfigDialog.createDialogArea(LaunchBarLaunchConfigDialog.java:191)
	at org.eclipse.jface.dialogs.TitleAreaDialog.createContents(TitleAreaDialog.java:166)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.eclipse.launchbar.ui.internal.LaunchBarUIManager.openConfigurationEditor(LaunchBarUIManager.java:134)
	at org.eclipse.launchbar.ui.controls.internal.ConfigSelector.handleEdit(ConfigSelector.java:156)
	at org.eclipse.launchbar.ui.controls.internal.CSelector$5.lambda$0(CSelector.java:265)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

**Comment by jonahgraham** [comment]
Thanks for the bug report! 

The issue here is that JUnit Test dialog is trying to display progress as part of its initialization, but there is no UI yet, hence NPEs. I think this is the fix, to surround existing code with this check:

```java
if (getShell() != null && getShell().isVisible()) {
```

and if false do this instead:

```java
PlatformUI.getWorkbench().getProgressService().run(fork, cancelable, runnable);
```

The full diff that I will turn into a PR at some point (unless someone else wants to pick that up)

```diff
diff --git a/launchbar/org.eclipse.launchbar.ui/src/org/eclipse/launchbar/ui/internal/LaunchBarLaunchConfigDialog.java b/launchbar/org.eclipse.launchbar.ui/src/org/eclipse/launchbar/ui/internal/LaunchBarLaunchConfigDialog.java
index 59d055fb03..1a2fdb486b 100644
--- a/launchbar/org.eclipse.launchbar.ui/src/org/eclipse/launchbar/ui/internal/LaunchBarLaunchConfigDialog.java
+++ b/launchbar/org.eclipse.launchbar.ui/src/org/eclipse/launchbar/ui/internal/LaunchBarLaunchConfigDialog.java
@@ -49,6 +49,7 @@ import org.eclipse.swt.widgets.Control;
 import org.eclipse.swt.widgets.Label;
 import org.eclipse.swt.widgets.Shell;
 import org.eclipse.swt.widgets.Text;
+import org.eclipse.ui.PlatformUI;
 
 public class LaunchBarLaunchConfigDialog extends TitleAreaDialog implements ILaunchBarLaunchConfigDialog {
 
@@ -325,24 +326,28 @@ public class LaunchBarLaunchConfigDialog extends TitleAreaDialog implements ILau
        @Override
        public void run(boolean fork, boolean cancelable, IRunnableWithProgress runnable)
                        throws InvocationTargetException, InterruptedException {
-               Control lastControl = getShell().getDisplay().getFocusControl();
-               if (lastControl != null && lastControl.getShell() != getShell()) {
-                       lastControl = null;
-               }
-               getButton(IDialogConstants.OK_ID).setEnabled(false);
-               getButton(IDialogConstants.CANCEL_ID).setEnabled(false);
-               pmPart.attachToCancelComponent(null);
+               if (getShell() != null && getShell().isVisible()) {
+                       Control lastControl = getShell().getDisplay().getFocusControl();
+                       if (lastControl != null && lastControl.getShell() != getShell()) {
+                               lastControl = null;
+                       }
+                       getButton(IDialogConstants.OK_ID).setEnabled(false);
+                       getButton(IDialogConstants.CANCEL_ID).setEnabled(false);
+                       pmPart.attachToCancelComponent(null);
 
-               try {
-                       ModalContext.run(runnable, fork, pmPart, getShell().getDisplay());
-               } finally {
-                       pmPart.removeFromCancelComponent(null);
-                       getButton(IDialogConstants.OK_ID).setEnabled(true);
-                       getButton(IDialogConstants.CANCEL_ID).setEnabled(true);
-                       if (lastControl != null) {
-                               lastControl.setFocus();
+                       try {
+                               ModalContext.run(runnable, fork, pmPart, getShell().getDisplay());
+                       } finally {
+                               pmPart.removeFromCancelComponent(null);
+                               getButton(IDialogConstants.OK_ID).setEnabled(true);
+                               getButton(IDialogConstants.CANCEL_ID).setEnabled(true);
+                               if (lastControl != null) {
+                                       lastControl.setFocus();
+                               }
+                               updateButtons();
                        }
-                       updateButtons();
+               } else {
+                       PlatformUI.getWorkbench().getProgressService().run(fork, cancelable, runnable);
                }
        }
 
```
