### ISSUE TITLE
Installer OOmph Script CDT for Development not working,  "Cannot complete the install because one or more required items could not be found."

### ISSUE THREAD

**Issue by SpaceMaster85** [eclipse-cdt/cdt#571]
**Describe the bug**
The installer script for CDT for Development fails during the setup of the workspace.

**To Reproduce**
1. Install newest Eclipse Installer
2. Goto https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-cdt/cdt/main/releng/CDTConfiguration.setup&show=true

4. Start Installer with "Install Using Copy and Paste" link https://raw.githubusercontent.com/eclipse-cdt/cdt/main/releng/CDTConfiguration.setup

5. Eclipse is installed correct
6. Setup of workspace fails
![image](https://github.com/eclipse-cdt/cdt/assets/19744998/8e92ddcb-6b92-478f-9fa6-210926c76c5b)

Fetching content.xml.xz from https://download.eclipse.org/egit/updates-nightly/ (26,08kB)
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:151)
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:905)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
    ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1695638802989
    ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: C/C++ Development Tools Core 8.3.0.202309011525 (org.eclipse.cdt.core 8.3.0.202309011525) requires 'osgi.bundle; org.eclipse.core.contenttype [3.8.200,4.0.0)' but it could not be found
    ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
      ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1695638802989
      ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.cdt.core 0.0.0

**Expected behavior**
The workspace setup process is finished and all packages were installed

**Version Information (please complete the following information):**
 - Win10 Pro
 - Eclipse IDE for Eclipse Committers (includes Incubating components), Version: 2023-09 (4.29.0), Build id: 20230907-1323

Thank you for your work and this project!

**Comment by jonahgraham** [comment]
Hi @SpaceMaster85 Thanks for the bug report.

AFAICT the installer works, but the issue is probably which target platform to use. The current main branch of CDT needs 2023-09 as the target platform to work and based on the error message you are getting you are probably using an older  target platform (perhaps 2023-06 or older?)

![image](https://github.com/eclipse-cdt/cdt/assets/679236/8acc8c1a-b84f-493f-a9d5-48d343403361)

Choosing 2023-09 should be resolved, and you can see that in action here:

![image](https://github.com/eclipse-cdt/cdt/assets/679236/680d6223-d603-4e43-a039-0b544911a1b0)

A couple of notes:

- In trying this I realized there was another mistake in the setup that leads to API errors, I have fixed it in #572 
- The CDT main branch does not yet work with the 2023-12 target platform as there have been some changes in Eclipse Platform that we need to resolve still. That normally happens in the days leading up to the next published build for CDT, CDT 11.4.0 M1 on Oct 2. PRs more than welcome if someone else wants to resolve the 2023-12 target platform issues.

**Comment by jonahgraham** [comment]
PS I am not very satisfied with the above answer. In practice only one version of "Target Platform" can work here, so presenting all the options is less than ideal.

@merks - CDT's main branch generally only works with the "correct" version of the Eclipse Platform, for now we have the following in the CDT.setup:

https://github.com/eclipse-cdt/cdt/blob/0d85f6c07b6dfefc7b560f9f8bdc9c689fc699b6/releng/CDT.setup#L74-L78

Do you have a recommendation what a good way to make sure that user's don't select the "wrong" version?

**Comment by merks** [comment]
This is what the platform does:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/bf4b5887873761e6ed7109bee69be350253c05a5/oomph/Platform.setup#L74-L83

I.e., it doesn't just set the default value but rather sets the value such that there is no prompted choice. 

You could instead do that in the configuration setup if you sometimes wish there to be  a choice.

**Comment by jonahgraham** [comment]
Thanks @merks - I have changed the UI to not prompt for target platform anymore.

**Comment by jonahgraham** [comment]
@SpaceMaster85 thanks for having reported this issue - hopefully with the change I made it will be easier to setup now.

**Comment by SpaceMaster85** [comment]
I can confirm that it is working now as intended. Thank you for your effort!
