### ISSUE TITLE
Recursive setProjectDescription from event listener,

### ISSUE THREAD

**Issue by LuluDavid** [eclipse-cdt/cdt#583]
**Describe the bug**
When calling manually ICProjectDescriptionManager#setProjectDescription(project, desc), it produces following stackTrace:  
`!ENTRY org.eclipse.cdt.core 1 0 2023-10-09 10:44:12.234
!MESSAGE Recursive setProjectDescription from event listener, project=P/<project_name>
!STACK 0
java.lang.Exception
	at org.eclipse.cdt.core.CCorePlugin.logStackTrace(CCorePlugin.java:1556)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.setProjectDescription(CProjectDescriptionManager.java:842)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.setProjectDescription(CProjectDescriptionManager.java:817)
	at org.eclipse.cdt.internal.core.settings.model.CExternalSettingsManager$1.run(CExternalSettingsManager.java:431)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager$5.run(CProjectDescriptionManager.java:508)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.runAtomic(CProjectDescriptionManager.java:504)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.runWspModification(CProjectDescriptionManager.java:472)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.runWspModification(CProjectDescriptionManager.java:444)
	at org.eclipse.cdt.internal.core.settings.model.CExternalSettingsManager.settingsChanged(CExternalSettingsManager.java:441)
	at org.eclipse.cdt.internal.core.settings.model.CExternalSettingContainerFactoryWithListener.notifySettingsChange(CExternalSettingContainerFactoryWithListener.java:48)
	at org.eclipse.cdt.internal.core.settings.model.CfgExportSettingContainerFactory.handleEvent(CfgExportSettingContainerFactory.java:270)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.notifyListeners(CProjectDescriptionManager.java:2190)
	at org.eclipse.cdt.internal.core.settings.model.SetCProjectDescriptionOperation.executeOperation(SetCProjectDescriptionOperation.java:155)
	at org.eclipse.cdt.internal.core.model.CModelOperation.execute(CModelOperation.java:346)
	at org.eclipse.cdt.internal.core.model.CModelOperation.run(CModelOperation.java:613)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.eclipse.cdt.internal.core.model.CModelOperation.runOperation(CModelOperation.java:644)
	at org.eclipse.cdt.internal.core.settings.model.AbstractCProjectDescriptionStorage.setProjectDescription(AbstractCProjectDescriptionStorage.java:209)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionStorageManager.setProjectDescription(CProjectDescriptionStorageManager.java:153)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.setProjectDescription(CProjectDescriptionManager.java:867)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.setProjectDescription(CProjectDescriptionManager.java:817)
	at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.setProjectDescription(CProjectDescriptionManager.java:810)
...
`

**To Reproduce**
Call ICProjectDescriptionManager#setProjectDescription(project, desc) on any project in the workspace.

**Expected behavior**
ICProjectDescriptionManager#setProjectDescription should not call itself back.

**Version Information (please complete the following information):**
 - OS and OS Version/extra details: Linux, Ubuntu 20.04
 - Eclipse Version from Help -> About : 2022-06
 - CDT Version from Help -> About -> Installation Details -> Features tab : 10.7.0  
 This is not state of the art but it seems CExternalSettingsManager has not been modified for quite a long time, I could check it still occurs on more recent versions if need be.

**Additional context**
It seems ICProjectDescriptionManager#setProjectDescription notifies its listener CfgExportSettingContainerFactory which notifies its listener CExternalSettingsManager which in its #settingsChanged first collects all projects in the workspace with #createCfgListsForEvent &  updates their respective descriptions somehow, then to set these descriptions with #setProjectDescription, which causes the error as the thread was already setting a description.  
It seems this bug has already been encountered a long time ago:  https://bugs.eclipse.org/bugs/show_bug.cgi?id=434040

**Comment by jonahgraham** [comment]
Thanks for the bug report @LuluDavid.

Do you have any ideas on how to fix this?

**Comment by LuluDavid** [comment]
Hi @jonahgraham, I guess a good way to solve this would be to move the call to CProjectDescriptionManager#notifyListeners from SetCProjectDescriptionOperation to CProjectDescriptionManager#setProjectDescription(IProject, ICProjectDescription, int, IProgressMonitor) after the lock is released at the end of the function.  
I do not know much about this class's workflow & I noticed that SetCProjectDescriptionOperation also calls AbstractCProjectDescriptionStorage#fireAboutToApplyEvent & AbstractCProjectDescriptionStorage#fireDataAppliedEvent, so there might be the same problem with these callbacks too.  
Maybe the solution is just to remove description updates from CExternalSettingsManager...
