### ISSUE TITLE
Changing Debug contexts breaks Disassembly view

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt/cdt#603]
**Describe the bug**

The disassembly view stops working if the debug context changes. This can be exceptions (see the end of report for examples) or simply corrupt displaying in the view

**To Reproduce**

1. Start two debug sessions
2. Open disassembly view
3. Switch between frames in the two sessions
4. Observe exceptions in the error log

**Expected behavior**

Disassembly works with multiple sessions.

**Screenshots**

Example of the view broken:

![image](https://github.com/eclipse-cdt/cdt/assets/679236/42789763-0933-4a0b-8d49-8eb86c0b4c1d)

**Version Information (please complete the following information):**
 - OS and OS Version/extra details: All platforms
 - Eclipse Version from Help -> 2023-09 (it works in 2023-06)
 - CDT Version from Help -> About -> Installation Details -> Features tab 11.3.0 (works in 11.2.0)

**Additional context**

See [error log](https://github.com/eclipse-cdt/cdt/files/13169594/disassembly.log) for some exceptions that are observed.

**Comment by jonahgraham** [comment]
With better exception handling (see https://github.com/eclipse-cdt/cdt/pull/604) the underlying exception for the items in the error log looks like:

```java
Caused by: org.eclipse.jface.text.BadLocationException: Offset > length: 79 > 0
	at org.eclipse.jface.text.ListLineTracker.getLineNumberOfOffset(ListLineTracker.java:141)
	at org.eclipse.jface.text.AbstractLineTracker.getLineNumberOfOffset(AbstractLineTracker.java:246)
	at org.eclipse.jface.text.AbstractDocument.getLineOfOffset(AbstractDocument.java:863)
	at org.eclipse.cdt.dsf.debug.internal.ui.disassembly.provisional.DisassemblyViewer.revealOffset(DisassemblyViewer.java:318)
	... 31 more
```

**Comment by jonahgraham** [comment]
Additional issues were identified caused by the recreating the document on context changed. In particular some places in the code were caching the initial document rather than fetching it from the editor part.
