### ISSUE TITLE
An internal error occurred during: "Launching Eclipse Application". Cannot invoke "java.util.List.stream()" because the return value of "java.util.Map.get(Object)" is null

### ISSUE THREAD

**Issue by VenoVeno** [eclipse-cdt/cdt#697]
I followed the steps mentioned in https://github.com/eclipse-cdt/cdt/blob/cdt_11_0/CONTRIBUTING.md. I have done "Setup CDT for development with Oomph"

When i try to debug configuration with "Software installation" flag turned on.

Error Message:

An internal error occurred during: "Launching Eclipse Application".

Exception Stack Trace:
```
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "java.util.Map.get(Object)" is null
	at org.eclipse.pde.internal.core.P2Utils.createFeatureIUs(P2Utils.java:571)
	at org.eclipse.pde.internal.core.P2Utils.createProfile(P2Utils.java:493)
	at org.eclipse.pde.internal.launching.launcher.LaunchConfigurationHelper.createConfigIniFile(LaunchConfigurationHelper.java:219)
	at org.eclipse.pde.launching.EclipseApplicationLaunchConfiguration.getProgramArguments(EclipseApplicationLaunchConfiguration.java:123)
	at org.eclipse.pde.launching.AbstractPDELaunchConfiguration.launch(AbstractPDELaunchConfiguration.java:152)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:805)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1038)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Session data:
```
eclipse.buildId=4.31.0.20240201-1200
java.version=17.0.9
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_IN
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.committers.product -data /home/user/CDT-Development-Mode/ws
```

Thanks,
Veno.

**Comment by jonahgraham** [comment]
I can reproduce this - it is certainly a bug in https://github.com/eclipse-equinox/p2 - but exposed by something in CDT (probably one of our plugins having an expected config). If someone can track down which plug-in is the problem then submitting a bug to p2 is more likely to get fixed.

> When i try to debug configuration with "Software installation" flag turned on.

To confirm - this implies that with "Software installation" flag turned **off** it works ok?

**Comment by jonahgraham** [comment]
This problem has been reported and fixed in https://github.com/eclipse-pde/eclipse.pde/pull/1114

You don't need to use the latest Eclipse when developing CDT, you can use the latest released one (i.e 2023-12)

**Comment by jonahgraham** [comment]
Or you can add https://download.eclipse.org/eclipse/updates/4.31-I-builds/ to available software sites and check for and install updates to pick up the fix.
